image: registry.gitlab.com/junte/docker-hub/docker:19

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:${CI_PIPELINE_ID}
  DOCKER_TEST_IMAGE: $CI_REGISTRY_IMAGE/tmp:test-${CI_PIPELINE_ID}
  DOCKER_CACHE_IMAGE: $CI_REGISTRY_IMAGE/tmp:latest

stages:
  - pre_build
  - build
  - test

lint:docker:
  image: hadolint/hadolint:v1.19.0-44-gf364c91-debian
  stage: pre_build
  script:
    - hadolint deploy/Dockerfile

lint:golang:
  image: golangci/golangci-lint:v1.33
  stage: pre_build
  script:
    - golangci-lint run

build:
  stage: build
  services:
    - registry.gitlab.com/junte/docker-hub/docker:19-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $DOCKER_CACHE_IMAGE || true
    - docker build --cache-from $DOCKER_CACHE_IMAGE -t $DOCKER_TEST_IMAGE -t $DOCKER_CACHE_IMAGE --target builder .
    - docker build --cache-from $DOCKER_CACHE_IMAGE -t $DOCKER_IMAGE .
    - docker push $DOCKER_TEST_IMAGE
    - docker push $DOCKER_IMAGE
    - docker push $DOCKER_CACHE_IMAGE

test:
  stage: test
  image: $DOCKER_TEST_IMAGE
  script:
    - go test -p 1  -v ./...
