version: "3.2"


services:
  executor:
    build: .
    command: ["./app"]
    ports:
      - 7788:7788
    volumes:
      - ./config.yaml:/root/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
